name: DeeFeenHC
version: 2.1.0
main: cz.deefeen.hardcore.HardcorePlugin
api-version: '1.21.5'
author: deefeen
description: Hardcore roguelike plugin - doomsday countdown, stats, soul insurance, scoreboard.
commands:
  hc:
    description: HardcoreWipe admin prikazy
    usage: /<command> stat reset
  soulinsure:
    description: Obětuj Totem oživení pro zrušení wipu
    usage: /<command>
  deadlist:
    description: Zobrazí historii wipe runů
    usage: /<command>
